baseURL = "https://slapekm.com/"
languageCode = "en"
title = "Mariusz SÅ‚apek"
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Mariusz SÅ‚apek"
description = "My personal blog"
author = "Mariusz SÅ‚apek"

defaultTheme = "auto"
disableThemeToggle = false

ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false
mainSections = ["posts"]

  [params.homeInfoParams]
  Title = "Hello World! ðŸ‘‹"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/slapekm"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://linkedin.com/in/slapekm"

  [[params.socialIcons]]
  name = "spotify"
  url = "https://open.spotify.com/user/slapekm"

  [[params.socialIcons]]
  name = "filmweb"
  url = "https://www.filmweb.pl/user/mslapek"

  [[params.socialIcons]]
  name = "lastfm"
  url = "https://www.last.fm/user/slapekm"

  [[params.socialIcons]]
  name = "soundcloud"
  url = "https://soundcloud.com/slapekm"

  [[params.socialIcons]]
  name = "strava"
  url = "https://www.strava.com/athletes/slapekm"

  [[params.socialIcons]]
  name = "leetcode"
  url = "https://leetcode.com/u/slapekm/"

  [[params.socialIcons]]
  name = "kaggle"
  url = "https://www.kaggle.com/slapekm"

  [[params.socialIcons]]
  name = "chess"
  url = "https://www.chess.com/member/slapekm"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 20

[outputs]
home = ["HTML", "RSS", "JSON"]
